### ISSUE TITLE
BadRequestKeyError  werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. KeyError: 'code'

### ISSUE THREAD

**Issue by mthibode13** [Danmou/onenote_export#19]
I get to the login screen, but after putting in my user name to sign in I get this in the browser session...

Traceback (most recent call last)

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__

    return self.wsgi_app(environ, start_response)

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app

    response = self.handle_exception(e)

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app

    response = self.full_dispatch_request()

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request

    rv = self.dispatch_request()

    File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) [Open an interactive python shell in this frame] 

    File "/Users/mthibode/onenote_export/onenote_export.py", line 232, in main_logic

    code = flask.request.args['code']

    File "/opt/homebrew/lib/python3.9/site-packages/werkzeug/datastructures.py", line 375, in __getitem__

    raise exceptions.BadRequestKeyError(key)

    werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
    KeyError: 'code'

**Comment by mthibode13** [comment]
Ran through procedures again and it worked well. Not sure what went wrong.
