### ISSUE TITLE
Flask error

### ISSUE THREAD

**Issue by tshort** [Danmou/onenote_export#2]
I got the following error on windows:

```
PS C:\tmp\tmp\onenote_export> python onenote_export.py
 * Serving Flask app "onenote_export" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 165-160-096
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Jan/2020 12:40:29] "GET / HTTP/1.1" 307 -
127.0.0.1 - - [20/Jan/2020 12:40:29] "GET /login HTTP/1.1" 307 -
Got 4 notebooks.
Opening notebook Course-2015-11-17
  Got 7 sections.
  Opening section Introduction
    Got 8 pages.
    Opening page 0_Course background
      Got content of length 4584
      Downloaded image of 5213168 bytes.
      Downloaded image of 40491 bytes.
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?code= HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\tmp\tmp\onenote_export\onenote_export.py", line 183, in main_logic
    f.write(content)
  File "C:\Users\user\scoop\apps\python\3.8.1\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffc' in position 993: character maps to <undefined>
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by tshort** [comment]
If I keep restarting the python script and reloading the browser window, it gets farther each time.

**Comment by mp68** [comment]
@tshort  Please remove your token from your post in line: `127.0.0.1 - - [20/Jan/2020 12:41:00] "GET /getToken?code=****`
This could grant a foreign person access to your account

**Comment by tshort** [comment]
Thanks for the heads up, @mp68. (In the original, I had deleted some bits of it, but complete deletion is better.)

**Comment by Danmou** [comment]
The problem is due to the default file encoding on Windows. It should be fixed in the latest master, let me know if it works.

**Comment by tshort** [comment]
Working great on master!
